language: ruby
cache: bundler

before_script:
  - sh -c "cd ext && bundle exec rake compile"

matrix:
  include:
    - rvm: 2.4
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.6
      env: TRENNI_PREFER_FALLBACK=y
    - rvm: 2.6
      env: COVERAGE=Summary
    - rvm: 2.7
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: truffleruby
  allow_failures:
    - rvm: truffleruby
    - rvm: ruby-head
    - rvm: jruby-head
