language: ruby
sudo: false

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - sh -c "cd ext && rake compile"

rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
  - jruby-head
  - rbx-2

env:
  - COVERAGE=true
  - COVERAGE=true TRENNI_PREFER_FALLBACK=y
matrix:
  allow_failures:
    - rvm: "rbx-2"
    - rvm: "ruby-head"
    - rvm: "jruby-head"
