language: ruby
sudo: false
before_install:
  - gem install bundler
  - gem update bundler
before_script:
  - rake
script:
  - bundle exec rake test
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - 2.4.0
  - ruby-head
  - jruby-head
  - rbx-2
env:
  - COVERAGE=true
  - COVERAGE=true TRENNI_PREFER_FALLBACK=y
matrix:
  allow_failures:
    - rvm: "rbx-2"
    - rvm: "ruby-head"
    - rvm: "jruby-head"
